(custom-set-variables
 '(auto-fill-function 'do-auto-fill t)
 '(byte-compile-warnings 'nil)
 '(epg-pinentry-mode 'loopback)
 '(fill-column 80)
 '(global-display-fill-column-indicator-mode t)
 '(global-font-lock-mode nil)
 '(indent-tabs-mode nil)
 '(menu-bar-mode 'nil)
 '(mode-line-modes nil t)
 '(org-agenda-files '("~/notes"))
 '(org-agenda-include-diary t)
 '(org-log-note-clock-out t)
 '(org-log-done 'note)
 '(org-clock-mode-line-total 'current)
 '(package-archives
   '(("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa.org/packages/")))
 '(package-selected-packages
   '(clang-format pass pinentry powershell groovy-mode csharp-mode racket-mode
                  markdown-mode cmake-mode ws-butler))
 '(password-store-password-length 10)
 '(sql-ms-program "sqlcmd")
 '(sql-sqlite-options '("-interactive"))
 '(tool-bar-mode 'nil)
 '(tramp-remote-path '(tramp-own-remote-path))
 '(tramp-sh-extra-args nil))
(custom-set-faces)
