#+begin_comment
This is an easy template based on the org-mode website's instructions to
build beamer presentations with org mode and latex.

At the time of writing this the tutorial is located here
https://orgmode.org/worg/exporters/beamer/tutorial.html

It was generated using `C-c C-e # default` then the extra tags were added
from the tutorial.  Generally, all I want to do is copy this out and start
hacking up my slides so I changed some of the default #+options to my
preference, mocked out the generated title, and removed some information I
don't need. This file should be easy to copy out and start immediately
working on a presentation.
#+end_comment

#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:nil e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+options: tags:t tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: PRESENTATION TEMPLATE
#+author: author
#+email: email
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+cite_export:

#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [bigger]

#+options: H:2

#+columns: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

* Introduction
** A simple slide
This slide consists of some text with a number of bullet points:

- the first, very *important*, point!
- the previous point shows the use of the special markup which
  translates to the Beamer specific /alert/ command for highlighting
  text.


The above list could be numbered or any other type of list and may
include sub-lists.
